version: '3'
services:
  digirunner:
    image: tpisoftwareopensource/digirunner-open-source
    ports:
      - "31080:18080"
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./dgr-data:/opt/digirunner/db